# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '5000:5000'
    environment:
      - FrontendUrl=${FrontendUrl}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience}
      - Jwt__Key=${Jwt__Key}
      - Jwt__ExpirationInDays=${Jwt__ExpirationInDays}
      - Jwt__RoleClaimType=${Jwt__RoleClaimType}
      - Jwt__NameClaimType=${Jwt__NameClaimType}
      - ConnectionStrings__DefaultConnection=${ConnectionStrings__DefaultConnection}
      - EmailSettings__Server=${EmailSettings__Server}
      - EmailSettings__Port=${EmailSettings__Port}
      - EmailSettings__Username=${EmailSettings__Username}
      - EmailSettings__Password=${EmailSettings__Password}