services:
  backend:
    image: xariif/engineering-work-backend:latest
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

  frontend:
    image: xariif/engineering-work-frontend:latest
    ports:
      - "8080:80"
    restart: always