name: Deploy .NET Application to Linux Server

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: Linux Server

    steps:
    - name: Show environment variables on server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          echo "Wszystkie zmienne środowiskowe na serwerze:"
          printenv

    - name: Create appsettings.Production.json
      run: |
        echo '${{ secrets.APPSETTINGS_PROD_JSON }}' > ./backend/appsettings.Production.json

    - name: Create frontend .env
      run: |
        echo '${{ secrets.FRONTEND_ENV }}' > ./frontend/.env

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore ./backend/backend.csproj

    - name: Build backend
      run: dotnet build ./backend/backend.csproj -c Release

    - name: Publish backend
      run: dotnet publish ./backend -c Release -o ./publish/backend

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci --force

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    - name: Copy backend to server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "./publish/backend/*"
        target: "/var/www/yourapp/backend/"

    - name: Copy frontend to server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "./frontend/dist/*"
        target: "/var/www/yourapp/frontend/"

    - name: Restart backend service
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
         sudo systemctl restart yourapp.service